module.exports = {
  analytics: ['https://filters.adtidy.org/extension/chromium/filters/3.txt'],
  personalization: [
    'https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt',
    'https://www.fanboy.co.nz/fanboy-cookiemonster.txt',
    'https://raw.github.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt',
    'https://raw.githubusercontent.com/liamja/Prebake/master/quiet.txt',
    'https://easylist.to/easylist/fanboy-annoyance.txt',
    'https://www.i-dont-care-about-cookies.eu/abp/',
  ],
  advertising: [
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_adservers.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_thirdparty.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_thirdparty_popup.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_adservers_popup.txt',
  ],
  other: [
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_block_dimensions.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_block_popup.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_hide.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_specific_block.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_specific_block_popup.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_specific_hide.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_whitelist.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_whitelist_dimensions.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_whitelist_general_hide.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_whitelist_popup.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_thirdparty.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_thirdparty_international.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_whitelist.txt',
    'https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_whitelist_international.txt',
  ],
};
